project_name: remote

build:
  main: cmd/remote/main.go
  binary: remote
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386

  ignore:
    - goos: darwin
      goarch: 386
  ldflags:
    -X main.version={{.Version}}

archive:
  format_overrides:
    - goos: windows
      format: zip

nfpm:
  vendor: TTP
  homepage: https://ttp.sh/
  maintainer: Thomas Albrighton <tom@ttp.sh>

  formats:
    - deb
    - rpm

  license: MIT

brew:
  # Reporitory to push the tap to.
  github:
    owner: ThatTomPerson
    name: homebrew-tap