project_name: remote

build:
  main: cmd/remote/main.go
  binary: remote
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386

  ignore:
    - goos: darwin
      goarch: 386

archive:
  format_overrides:
    - goos: windows
      format: zip

nfpm:
  vendor: TTP
  homepage: https://ttp.sh/
  maintainer: Thomas Albrighton <tom@ttp.sh>

  formats:
    - deb
    - rpm

  license: MIT

brew:
  # Reporitory to push the tap to.
  github:
    owner: ThatTomPerson
    name: homebrew-tap

snapcraft:
  grade: stable
  confinement: strict
  summary: SSH into a Docker Container running in an ECS Cluster
  description: |
    SSH into a Docker Container running in an ECS Cluster
  apps:
    remote:
      plugs: ["home", "network"]

release:
  draft: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^refactor'